import os
import sys
import subprocess
import joblib
import numpy as np
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

# ============================================================
# APP INITIALIZATION
# ============================================================

app = FastAPI(
    title="Customer Segmentation API",
    description="Serves predictions from a pretrained Random Forest model.",
    version="1.0.0"
)

# Allow the Streamlit frontend (and local dev tools) to call this API.
# Update allow_origins with your deployed frontend URL in production.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],          # tighten this in production, e.g. ["http://localhost:8501"]
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ============================================================
# PATHS & FEATURE ORDER
# ============================================================

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
MODEL_PATH = os.path.join(BASE_DIR, "models", "random_forest.pkl")
SCALER_PATH = os.path.join(BASE_DIR, "models", "scaler.pkl")

FEATURES = [
    "Recency",
    "Frequency",
    "Monetary",
    "Avg_Discount_Rate",
    "Unique_Product_Categories",
    "Total_Profit",
]

SEGMENT_INFO = {
    0: {
        "name": "High-Value Profitable",
        "description": (
            "Customers with strong spending and profitability. "
            "They are highly valuable to the business."
        ),
        "action": (
            "Prioritize retention, loyalty programs and personalized "
            "recommendations. Avoid unnecessary discounts."
        ),
    },
    1: {
        "name": "At-Risk Valuable",
        "description": (
            "Historically valuable customers who have become highly inactive."
        ),
        "action": (
            "Launch win-back campaigns, personalized offers and "
            "reactivation campaigns."
        ),
    },
    2: {
        "name": "Recent Low-Value",
        "description": (
            "Recent customers with low purchase frequency and "
            "relatively low spending."
        ),
        "action": (
            "Encourage repeat purchases through cross-selling, "
            "product recommendations and loyalty programs."
        ),
    },
    3: {
        "name": "High-Revenue / Low-Profit",
        "description": (
            "Customers with very high purchasing frequency and revenue "
            "but comparatively low profitability."
        ),
        "action": (
            "Investigate product margins, discounts and cost structure. "
            "Focus on improving profitability rather than simply increasing sales."
        ),
    },
    4: {
        "name": "Discount-Sensitive",
        "description": (
            "Recent low-value customers who use relatively higher discounts."
        ),
        "action": (
            "Reduce discount dependency and test targeted offers, "
            "bundles and loyalty incentives."
        ),
    },
}

# ============================================================
# LOAD MODEL & SCALER (ONCE, AT STARTUP)
# ============================================================

model = None
scaler = None
load_error = None

try:
    model = joblib.load(MODEL_PATH)
    scaler = joblib.load(SCALER_PATH)
except Exception as e:
    # Don't crash the app on import; report the problem via /health instead.
    load_error = str(e)


# ============================================================
# REQUEST / RESPONSE SCHEMAS
# ============================================================

class CustomerInput(BaseModel):
    Recency: float = Field(..., ge=0, description="Days since last purchase")
    Frequency: float = Field(..., ge=0, description="Number of purchases made")
    Monetary: float = Field(..., ge=0, description="Total spending amount")
    Avg_Discount_Rate: float = Field(..., ge=0, le=1, description="Average discount rate, 0-1")
    Unique_Product_Categories: float = Field(..., ge=0, description="Number of distinct categories purchased")
    Total_Profit: float = Field(..., description="Total profit generated by the customer")

    class Config:
        json_schema_extra = {
            "example": {
                "Recency": 100.0,
                "Frequency": 2.0,
                "Monetary": 500.0,
                "Avg_Discount_Rate": 0.10,
                "Unique_Product_Categories": 2.0,
                "Total_Profit": 100.0,
            }
        }


class PredictionResponse(BaseModel):
    cluster: int
    segment_name: str
    description: str
    recommendation: str


class HealthResponse(BaseModel):
    status: str
    model_loaded: bool
    scaler_loaded: bool
    detail: str | None = None


# ============================================================
# ENDPOINTS
# ============================================================

@app.get("/health", response_model=HealthResponse)
def health_check():
    """Simple readiness check for the API and its model artifacts."""
    ok = model is not None and scaler is not None
    return HealthResponse(
        status="ok" if ok else "error",
        model_loaded=model is not None,
        scaler_loaded=scaler is not None,
        detail=load_error if not ok else None,
    )


@app.post("/predict", response_model=PredictionResponse)
def predict(customer: CustomerInput):
    """Predict a customer's segment from their RFM + behavioral features."""

    if model is None or scaler is None:
        raise HTTPException(
            status_code=503,
            detail=f"Model artifacts not loaded: {load_error}",
        )

    try:
        # Preserve the exact training feature order.
        input_array = np.array([[
            customer.Recency,
            customer.Frequency,
            customer.Monetary,
            customer.Avg_Discount_Rate,
            customer.Unique_Product_Categories,
            customer.Total_Profit,
        ]])

        input_scaled = scaler.transform(input_array)
        prediction = model.predict(input_scaled)
        cluster = int(prediction[0])

        segment = SEGMENT_INFO.get(cluster)
        if segment is None:
            raise HTTPException(
                status_code=500,
                detail=f"Model returned an unknown cluster id: {cluster}",
            )

        return PredictionResponse(
            cluster=cluster,
            segment_name=segment["name"],
            description=segment["description"],
            recommendation=segment["action"],
        )

    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Prediction failed: {str(e)}")


@app.get("/")
def root():
    return {"message": "Customer Segmentation API is running. See /docs for API documentation."}


# ============================================================
# AUTO-LAUNCH STREAMLIT FRONTEND
# ============================================================
# Starts the Streamlit app as a subprocess when the API starts,
# so `uvicorn main:app --reload --port 8000` brings up both
# the backend and the frontend together.

STREAMLIT_PORT = 8501
FRONTEND_APP_PATH = os.path.join(BASE_DIR, "..", "frontend", "app.py")

streamlit_process = None


def _port_in_use(port: int) -> bool:
    import socket
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        return s.connect_ex(("127.0.0.1", port)) == 0


@app.on_event("startup")
def launch_streamlit():
    global streamlit_process

    if _port_in_use(STREAMLIT_PORT):
        # Already running (e.g. from a previous --reload cycle or manual start).
        return

    if not os.path.exists(FRONTEND_APP_PATH):
        print(f"[warning] Frontend app not found at {FRONTEND_APP_PATH}, skipping auto-launch.")
        return

    streamlit_process = subprocess.Popen(
        [
            sys.executable, "-m", "streamlit", "run", FRONTEND_APP_PATH,
            "--server.port", str(STREAMLIT_PORT),
            "--server.headless", "true",
        ]
    )
    print(f"[info] Streamlit frontend starting at http://127.0.0.1:{STREAMLIT_PORT}")


@app.on_event("shutdown")
def stop_streamlit():
    global streamlit_process
    if streamlit_process is not None and streamlit_process.poll() is None:
        streamlit_process.terminate()
        try:
            streamlit_process.wait(timeout=5)
        except subprocess.TimeoutExpired:
            streamlit_process.kill()